apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 # AMQP port
        - containerPort: 15672 # Management UI port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_PLUGINS
          value: opentelemetry
        - name: RABBITMQ_OTEL_TRACES_EXPORTER
          value: otlp
        - name: RABBITMQ_OTEL_TRACES_EXPORTER_OTLP_ENDPOINT
          value: https://api.honeycomb.io:443
        - name: RABBITMQ_OTEL_TRACES_EXPORTER_OTLP_HEADERS
          value: SU5aijCxMxzVhbFoL02BeD
        - name: RABBITMQ_OTEL_TRACES_SAMPLER
          value: always_on
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecommerce-app
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30672  # AMQP (For applications)
    name: amqp
  - port: 15672
    targetPort: 15672
    nodePort: 31672  # Management UI (For you)
    name: managementui

