apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: amqp 
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management-ui
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 31672 # Optional, Kubernetes assigns a port in the 30000–32767 range if not specified
