name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:  # This enables manual runs


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation

      - name: Build Docker Images
        run: |
          docker-compose -f Backend/docker-compose.yml build

      - name: Push Docker Images
        run: |
          docker-compose -f Backend/docker-compose.yml push
      
      - name: Decode and Save Kubeconfig
        run: |
            mkdir -p ~/.kube  # Ensure the .kube directory exists
            echo "$KUBECONFIG" | base64 --decode > ~/.kube/config

            # Ensure a valid context is set
            kubectl config use-context docker-desktop || kubectl config use-context minikube || echo "No valid context found"
    
            # Show the current context and verify the config
            kubectl config current-context
            kubectl config view --minify
        env:
            KUBECONFIG: ${{ secrets.KUBECONFIG }}





      - name: Verify Kubernetes Context
        run: kubectl config current-context

      - name: Run Shell Script to Apply Kubernetes Manifests
        run: |
          chmod +x Backend/Kubernetes/deployments/deploy-k8s.sh  # Make sure the script is executable
          ./Backend/Kubernetes/deployments/deploy-k8s.sh

      - name: Check Deployment Status
        run: kubectl get pods
